### ISSUE TITLE
xcodebuild archive -scheme "pod里的target" 后 包内容为空

### ISSUE THREAD

**Issue by Sparklehorse001** [WeijunDeng/Zabel#5]
zabel xcodebuild archive  -workspace CompileOptimizeDemo.xcworkspace -scheme JSONModel -configuration release -archivePath EXPORT_ARCHIVE_PATH

**Comment by WeijunDeng** [comment]
@Sparklehorse001 你好，麻烦确认一下 zabel 的版本，以及确认 release 的 configuration 是否正确。方便的话可以上传一下 Demo，谢谢。

**Comment by Sparklehorse001** [comment]
zabel 版本是1.0.5

**Comment by Sparklehorse001** [comment]
[CompileOptimizeDemo.zip](https://github.com/WeijunDeng/Zabel/files/7055676/CompileOptimizeDemo.zip)
辛苦帮忙看下问题

**Comment by Sparklehorse001** [comment]
** ARCHIVE SUCCEEDED ** [8.435 sec]

[ZABEL/I] duration = 13 s in stage build
[ZABEL/E] /CompileOptimizeDemo/Pods/Pods.xcodeproj should have config release
[ZABEL/I] keep cache 0 
[ZABEL/I] total add 0
[ZABEL/I] duration = 0 s in stage post
[ZABEL/I] duration = 13 s in stage all

**Comment by WeijunDeng** [comment]
Release 大写 R ？

**Comment by WeijunDeng** [comment]
先保证你的命令在不用zabel时是可用的。

**Comment by Sparklehorse001** [comment]
谢谢，改了之后有缓存了，不过想问下scheme设置成pod里的target后，EXPORT_ARCHIVE_PATH.xcarchive包内容是空的，我需要再修改什么吗？

**Comment by WeijunDeng** [comment]
1. 我理解是，archive 是 只针对 scheme 为 app 的；
2. 如果你确定是要编译一个 pod 为 .a 或者 .framework，则去掉 archive 直接 build 就可以
3. zabel 不限制 xcodebuild 的 scheme，也支持 archive 和 不 archive 。只不过是目前只对 Pods 里的 target 有缓存作用。

**Comment by Sparklehorse001** [comment]
嗯嗯，缓存里已经有.a文件，但archive时scheme更换为app，提示信息：[ZABEL/I] total 4 hit 0 miss 4 iteration 1。我应该如何命中缓存？

**Comment by WeijunDeng** [comment]
方法1，使用相同命令再编译一次
方法2，使用 pre 和 post 的高级用法

**Comment by Sparklehorse001** [comment]
好的，多谢。

**Comment by WeijunDeng** [comment]
具体的缓存 key 生成，可以查看 缓存目录下的 /xxx-123-456/message.txt
