### ISSUE TITLE
[疑似bug] zabel_get_target_md5_content，build_phases处理问题

### ISSUE THREAD

**Issue by ParryingDagger** [WeijunDeng/Zabel#6]
# 问题

https://github.com/WeijunDeng/Zabel/blob/main/lib/zabel.rb#L275-L283

build_phase在循环内没有用到，一直在处理target.source_build_phase.files_reference

**Comment by WeijunDeng** [comment]
好家伙，是个 bug ，我处理一下

**Comment by WeijunDeng** [comment]
https://github.com/WeijunDeng/Zabel/commit/6a965891f2f37b2712d3eb783939bebbed4125bc

**Comment by ParryingDagger** [comment]
改了之后有个坑，`PBXResourcesBuildPhase.files_references`返回的列表元素可能是`PBXFileReference`或`PBXVariantGroup`，后者没有`build_files`方法导致崩溃

**Comment by WeijunDeng** [comment]
@ParryingDagger 谢谢反馈，你有兴趣的话可以提个 pull request 来一起维护呀~

**Comment by 451222664** [comment]
/Users/xxx/.rvm/gems/ruby-2.7.5/gems/zabel-1.0.6/lib/zabel.rb:277:in `block (2 levels) in zabel_get_target_md5_content': undefined method `build_files' for #<Xcodeproj::Project::Object::PBXVariantGroup:0x00007f89513ffa70> (NoMethodError)****

**Comment by WeijunDeng** [comment]
get
